import './globals.css'
import { Raleway , Bitter } from 'next/font/google'
import Image from 'next/image'
import logo from 'public/vector.png'
import next from 'next/types';

const raleway = Raleway({ subsets: ['latin'] });
const bitter = Bitter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-white ${raleway.className}`}>
        {children}
      </body>

    </html>
  )
}
